### ISSUE TITLE
about your GO program checklist

### ISSUE THREAD

**Issue by prune998** [Depado/articles#34]
Hi,

- viper can be replaced by the simplest `github.com/namsral/flag` if you don't need a config file (config files are evil, see 12 factors)
- dep is "deprecated", use modules
- cobra have a strong application layout which makes your go code far less readable
- you forgot to add metrics (using the prometheus endpoint and `github.com/prometheus/client_golang/prometheus`). This is useful if your application is not a commandline tool
- you forgot to add tracing, which can also be helpful if it's not a commandline. Opentracing, Jaeger, Zipkin... or Opencensu which offer all of the above plus many other things

I would have commented on the blog directly, but your oauth tool against Github is requesting read and *write* to all my public repos, which is not going to happen.

**Comment by Depado** [comment]
Hi, thanks for your feedback! 
Just keep in mind this article is about my personal preferences and experiences :smile: 
A few points:

- From what I can see, `github.com/namsral/flag` also allows to bind against a config file. Viper is flexible enough to not account for config files or env variables if you don't need them. (It is my own personal choice to support all three because of my various use cases). I also chose Viper because of its coupling with Cobra. 
- Dep is not yet deprecated as modules are still in an experimental state. And even though now I'm using modules, at the time of writing this article, modules were not a thing and I didn't update the article since. But if you have a look at the posts I wrote since, you'll notice I spent a whole lot of time speaking about modules :smile: 
> Go 1.11 includes preliminary support for versioned modules as proposed here. Modules are an experimental opt-in feature in Go 1.11, with the plan of incorporating feedback and finalizing the feature for Go 1.13. Even though some details may change, future releases will support modules defined using Go 1.11 or 1.12.
> [Source](https://github.com/golang/go/wiki/Modules)
- Even though Cobra **can** generate a layout for your application when starting a project, it is absolutely not mandatory. You can even have all your Cobra stuff in your `main.go` there's no problem with that. 
- Indeed I forgot to add metrics even though I created a lib to automatically instrument a gin router with the proper labels : [ginprom](https://github.com/Depado/ginprom)
- As I never used tracing for myself I can't recommend or show a quick way of adding it. That's the way this article was written: my own experience and the things I do daily. I started looking at tracing (especially OpenTracing) some time ago, but still didn't have time to experiment.

As for the authorization required to comment you can also comment as anonymous. And if it requires `write` permission, it's because it needs to comment on this issue for you I guess :+1: But it's fine for you to answer here or on the issue dedicated to the article #23

**Comment by prune998** [comment]
Thanks for the reply and comments. I'll check Viper again then :)

Sound I wasn't able to comment as anonymous... maybe it's just me and sorry for that. 
You can close the issue.

**Comment by Depado** [comment]
Oh you're right, people can't comment as anonymous. Maybe I have a configuration issue on my side :thinking: 
Anyway thanks for the feedback, I'll modify the article to add a section about instrumentation with prometheus :+1:
